### ISSUE TITLE
Write permission for Github Actions TOC generator

### ISSUE THREAD

**Issue by Wrench56** [Greeley-Robotics/conventions#1]
I added a table of content (TOC) generator, however it is failing due to missing write permission (see logs). Currently I do not have the priviliges to update the permissions for the workflow.

<details>
<summary>Log</summary>
<pre>
==================================================
Version:  technote-space/toc-generator@v4.3.1
          3ba472e2cc699e92e6dba3f5ce758e1cde43fbc9
Event:    push
Action:   undefined
sha:      a8bd89710b295b0728835372eeb8de3bd2ac3901
ref:      refs/heads/main
owner:    Greeley-Robotics
repo:     conventions
==================================================

git config --global 'init.defaultBranch' main
Fetching...
Switching branch to [main]...
Running commands...
Checking diff...
Committing...
Pushing to Greeley-Robotics/conventions@main...
  git push origin main:refs/heads/main
    >> remote: Write access to repository not granted.
    >> fatal: unable to access 'https://github.com/Greeley-Robotics/conventions.git/': The requested URL returned error: 403
  
  Error: command [git push origin main:refs/heads/main] exited with code 128. message: remote: Write access to repository not granted.
  fatal: unable to access 'https://github.com/Greeley-Robotics/conventions.git/': The requested URL returned error: 403
  
      at Command.value [as execAsync] (/home/runner/work/_actions/technote-space/toc-generator/v4/lib/main.js:89037:31)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async GitHelper.value [as runCommand] (/home/runner/work/_actions/technote-space/toc-generator/v4/lib/main.js:89118:45)
      at async GitHelper.value [as push] (/home/runner/work/_actions/technote-space/toc-generator/v4/lib/main.js:89552:17)
      at async push (/home/runner/work/_actions/technote-space/toc-generator/v4/lib/main.js:96169:5)
      at async createCommit (/home/runner/work/_actions/technote-space/toc-generator/v4/lib/main.js:96[62](https://github.com/Greeley-Robotics/conventions/actions/runs/7771466343/job/21192794048#step:2:63)2:5)
      at async execute (/home/runner/work/_actions/technote-space/toc-generator/v4/lib/main.js:96816:28)
      at async main (/home/runner/work/_actions/technote-space/toc-generator/v4/lib/main.js:96845:5)
  Error: command [git push origin main:refs/heads/main] exited with code 128. message: remote: Write access to repository not granted.
  fatal: unable to access 'https://github.com/Greeley-Robotics/conventions.git/': The requested URL returned error: 403
  
      at Command.value [as execAsync] (/home/runner/work/_actions/technote-space/toc-generator/v4/lib/main.js:89037:31)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async GitHelper.value [as runCommand] (/home/runner/work/_actions/technote-space/toc-generator/v4/lib/main.js:89118:45)
      at async GitHelper.value [as push] (/home/runner/work/_actions/technote-space/toc-generator/v4/lib/main.js:89552:17)
      at async push (/home/runner/work/_actions/technote-space/toc-generator/v4/lib/main.js:96169:5)
      at async createCommit (/home/runner/work/_actions/technote-space/toc-generator/v4/lib/main.js:9[66](https://github.com/Greeley-Robotics/conventions/actions/runs/7771466343/job/21192794048#step:2:67)22:5)
      at async execute (/home/runner/work/_actions/technote-space/toc-generator/v4/lib/main.js:9[68](https://github.com/Greeley-Robotics/conventions/actions/runs/7771466343/job/21192794048#step:2:69)16:28)
      at async main (/home/runner/work/_actions/technote-space/toc-generator/v4/lib/main.js:96845:5)
  Error: command [git push origin main:refs/heads/main] exited with code 128. message: remote: Write access to repository not granted.
  fatal: unable to access 'https://github.com/Greeley-Robotics/conventions.git/': The requested URL returned error: 403
</pre>
</details>

**Comment by RZJournal** [comment]
Changed workflow permissions
